blog/urls.py
"""

@Author  : dilless
@Time    : 2018/7/12 1:21
@File    : urls.py
"""
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:blog_id>/', views.blog_article, name='blog_article')
]

image/urls.py
"""

@Author  : dilless
@Time    : 2018/7/18 19:39
@File    : urls.py
"""
from django.urls import path

from image import views

app_name = 'image'

urlpatterns = [
    path('upload-image/', views.upload_image, name='upload_image'),
    path('list-images/', views.list_images, name='list_images'),
    path('del-image/', views.del_image, name='del_image'),
    path('images/', views.falls_images, name='falls_images'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/models.py
from django.contrib.auth.models import User
from django.db import models
from slugify import slugify


class Image(models.Model):
    user = models.ForeignKey(User, related_name='images', on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    url = models.URLField()
    slug = models.SlugField(max_length=500, blank=True)
    description = models.TextField(blank=True)
    create_date = models.DateField(auto_now_add=True, db_index=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

image/forms.py
"""

@Author  : dilless
@Time    : 2018/7/18 19:15
@File    : forms.py
"""
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from slugify import slugify

from image.models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        labels = {
            'title': '标题',
            'url': '链接地址',
            'description': '描述',
        }

    # clean_<fieldname>方法用于处理<filedname>字段
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given url does not match valid image extension.')
        return url

    def save(self, commit=True, force_insert=False, force_update=False):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{0}.{1}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

image/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from image.forms import ImageForm
from image.models import Image


@login_required(login_url=reverse_lazy('account:user_login'))
@require_POST
def upload_image(request):
    form = ImageForm(request.POST)
    if form.is_valid():
        try:
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            return JsonResponse({'status': '1'})
        except:
            return JsonResponse({'status': '0'})


@login_required(login_url=reverse_lazy('account:user_login'))
def list_images(request):
    images = Image.objects.filter(user=request.user)
    paginator = Paginator(images, 5)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        images = current_page.object_list
    except PageNotAnInteger or EmptyPage:
        current_page = paginator.page(1)
        images = current_page.object_list
    return render(request, 'image/list_images.html', {
        'images': images,
        'page': current_page
    })


@login_required(login_url=reverse_lazy('account:user_login'))
@require_POST
def del_image(request):
    image_id = request.POST['image_id']
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('image:list_images')


def falls_images(request):
    images = Image.objects.all()
    return render(request, 'image/falls_images.html', {
        'images': images,
    })

image/templates/image/falls_images.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
  美图
{% endblock %}

{% block content %}
  <div>
    <link rel="stylesheet" href="{% static 'css/mansory.css' %}" type="text/css">
    <div id="my-gallery-container">
      {% for image in images %}
        <div class="falls_item h200" data-order="{{ image.id }}">
          {#      <img src="{{ image.image.url }}" alt="{{ image.description }}">#}
          <a href="javascript:void(0)"
             onclick="displayImage('{{ image.user }}', '{{ image.title }}', '{{ image.image.url }}', '{{ image.description }}', '{{ image.get_host }}')"><img
                  src="{{ image.image.url }}" alt="{{ image.description }}"></a>
          <p>{{ image.title }}</p>
        </div>
      {% endfor %}

    </div>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/mp.mansory.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#my-gallery-container").mpmansory(
                {
                    childrenClass: 'falls_item',
                    columnClasses: 'falls_padding',
                    breakpoints: {
                        lg: 3,
                        md: 4,
                        sm: 5,
                        xs: 12
                    },
                    distributeBy: {order: false, height: false, attr: 'data-order', attrOrder: 'desc'},
                }
            );
        });

        function displayImage(user, title, url, description, host) {
            layer.open({
                type: 1,
                title: title,
                skin: 'layui-layer-rim',
                area: ['800px', '800px'],
                content: '<div class="text-center"><img src="http://' + host + url + '"><p>发布者:' + user + '</p></div><div style="margin-left:10px;">' + description + '</div>',
            });
        }
    </script>
  </div>
{% endblock %}

image/templates/image/list_images.html
{% extends 'article/base.html' %}

{% load staticfiles %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block title %}
  图片列表
{% endblock %}

{% block content %}
  <div>
    <div>
      <p class="text-right">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
          添加图片
        </button>

        <!-- Modal add -->
      <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                      aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">添加图片</h4>
            </div>
            <form action="{% url 'image:upload_image' %}" method="post">
              {% csrf_token %}
              <div class="modal-body">
                <div class="form-group">
                  <label for="id_title" class="control-label">标题</label>
                  <div>
                    <input type="text" name="title" id="id_title" class="form-control">
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_url" class="control-label">地址</label>
                  <div>
                    <input type="text" name="url" id="id_url" class="form-control">
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_description" class="control-label">描述</label>
                  <div>
                    <textarea name="description" id="id_description" class="form-control"></textarea>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-primary">保存</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div>
      <table class="table table-hover">
        <tr>
          <td>序号</td>
          <td>标题</td>
          <td>图片</td>
          <td>操作</td>
        </tr>
        {% for image in images %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ image.title }}</td>
            {% thumbnail image.image '100x100' as img %}
            <td><img src="{{ img.url }}" alt="{{ image.description }}"></td>
            {% endthumbnail %}
            <td>
              <a data-toggle="modal" data-target="#delModal{{ image.id }}">
                <span class="glyphicon glyphicon-trash"></span>
              </a>
            </td>
          </tr>
          <div class="modal fade" id="delModal{{ image.id }}" tabindex="-1" role="dialog"
               aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                          aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">确认删除</h4>
                </div>
                <form action="{% url 'image:del_image' %}" method="post">
                  {% csrf_token %}
                  <div class="modal-body">
                    <input type="hidden" name="image_id" value="{{ image.id }}">
                    <p><strong>删除《{{ image.title }}》后无法恢复，请确认</strong></p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">确认</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        {% empty %}
          <p>还没有上传图片，请点击上面的按钮添加图片</p>
        {% endfor %}
      </table>
    </div>
  {% include 'paginator.html' %}
  </div>
{% endblock %}