article/urls.py
"""

@Author  : dilless
@Time    : 2018/7/16 1:25
@File    : urls.py
"""
from django.urls import path, re_path

from article import views

app_name = 'article'

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-article-column/', views.rename_article_column, name='rename_article_column'),
    path('del_article_column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('edit-article/<int:article_id>/', views.edit_article, name='edit-article'),
    path('list-article-titles/', views.list_article_titles, name='list_article_titles'),
    path('list-article-detail/<int:article_id>/<slug:slug>/', views.list_article_detail, name='list_article_detail'),
    path('like-article/', views.like_article, name='like_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    path('rename-article-tag/', views.edit_article_tag, name='rename_article_tag'),
]

blog/urls.py
"""

@Author  : dilless
@Time    : 2018/7/12 1:21
@File    : urls.py
"""
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:blog_id>/', views.blog_article, name='blog_article')
]

course/urls.py
"""

@Author  : dilless
@Time    : 2018/7/18 23:54
@File    : urls.py
"""
from django.urls import path

from course.views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, \
    CreateLessonView, ListLessonsView, DetailLessonView, StudentListLessonView

app_name = 'course'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('course-list/', CourseListView.as_view(), name='course_list'),
    path('manage-course/', ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(), name='delete_course'),
    path('create-lesson/', CreateLessonView.as_view(), name='create_lesson'),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name='list_lessons'),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name='detail_lesson'),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name='lessons_list'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.contrib.auth.models import User
from django.db import models
from slugify import slugify

from course.fields import OrderField


class Course(models.Model):
    user = models.ForeignKey(User, related_name='courses_user', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    student = models.ManyToManyField(User, related_name='courses_joined', blank=True)

    class Meta:
        ordering = ('-create_time',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


def user_directory_path(instance, filename):
    return 'courses/user_{0}/{1}'.format(instance.user.id, filename)


class Lesson(models.Model):
    user = models.ForeignKey(User, related_name='lesson_user', on_delete=models.CASCADE)
    course = models.ForeignKey(Course, related_name='lesson', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    video = models.FileField(upload_to=user_directory_path)
    description = models.TextField(blank=True)
    attach = models.FileField(blank=True, upload_to=user_directory_path)
    create_time = models.DateTimeField(auto_now_add=True)
    order = OrderField(blank=True, for_fields=['course'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}.{}'.format(self.order, self.title)

course/forms.py
"""

@Author  : dilless
@Time    : 2018/7/19 18:58
@File    : forms.py
"""
from django import forms

from course.models import Course, Lesson


class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('title', 'overview')

        labels = {
            'title': '标题',
            'overview': '概览',
        }


class CreateLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['course', 'title', 'video', 'description', 'attach']

        labels = {
            'course': '课程',
            'title': '标题',
            'video': '视频地址',
            'description': '视频描述',
            'attach': '附件',
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.filter(user=user)

course/views.py
import json

from braces.views import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, DeleteView
from django.views.generic.base import TemplateResponseMixin

from course.forms import CreateCourseForm, CreateLessonForm
from course.models import Course, Lesson


class AboutView(TemplateView):
    template_name = 'course/about.html'


class CourseListView(ListView):
    model = Course
    context_object_name = 'courses'
    template_name = 'course/course_list.html'


class UserMixin(object):
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


class UserCourseMixin(UserMixin, LoginRequiredMixin):
    model = Course
    login_url = reverse_lazy('account:user_login')


class ManageCourseListView(UserCourseMixin, ListView):
    context_object_name = 'courses'
    template_name = 'course/manage_course_list.html'


class CreateCourseView(UserCourseMixin, CreateView):
    # fields = ['title', 'overview']
    form_class = CreateCourseForm
    template_name = 'course/manage/create_course.html'

    def post(self, request, *args, **kwargs):
        form = CreateCourseForm(data=request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user = request.user
            new_course.save()
            return redirect('course:manage_course')
        return self.render_to_response({'form': form})


# 使用Post提交表单， url为 delete_course/<int:id>/即可
class DeleteCourseView(UserCourseMixin, DeleteView):
    context_object_name = 'course'
    # template_name = 'course/manage/delete_course_confirm.html'
    success_url = reverse_lazy('course:manage_course')


class CreateLessonView(LoginRequiredMixin, View):
    model = Lesson
    login_url = reverse_lazy('account:user_login')

    def get(self, request, *args, **kwargs):
        form = CreateLessonForm(user=self.request.user)
        return render(request, 'course/manage/create_lesson.html', {'form':form})

    def post(self, request, *args, **kwargs):
        form = CreateLessonForm(self.request.user, request.POST, request.FILES)
        if form.is_valid():
            new_lesson = form.save(commit=False)
            new_lesson.user = self.request.user
            new_lesson.save()
            return redirect('course:manage_course')


class ListLessonsView(LoginRequiredMixin, TemplateResponseMixin, View):
    login_url = reverse_lazy('account:user_login')
    template_name = 'course/manage/list_lessons.html'

    def get(self, request, course_id):
        course = get_object_or_404(Course, id=course_id)
        return self.render_to_response({'course': course})


class DetailLessonView(LoginRequiredMixin, TemplateResponseMixin, View):
    login_url = reverse_lazy('account:user_login')
    template_name = 'course/manage/detail_lesson.html'

    def get(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        return self.render_to_response({'lesson': lesson})


class StudentListLessonView(ListLessonsView):
    template_name = 'course/student_list_lessons.html'

    def post(self, request, *args, **kwargs):
        course = Course.objects.get(id=request.POST['course_id'])
        course.student.add(self.request.user)
        return HttpResponse('ok')

course/templates/course/about.html
{% extends 'base.html' %}

{% block title %}
关于本站
{% endblock %}

{% block content %}
<div class="text-center">
<h1>欢迎来到boge.me</h1>
<p>这是我的测试网站</p>
<p><a href="#">联系我</a></p>
<h2>感谢访问</h2>
</div>
{% endblock %}

course/templates/course/course_list.html
{% extends 'base.html' %}

{% block title %}
课程列表
{% endblock %}

{% block content %}
<div>
<table class="table table-hover">
  <tr>
    <td>序号</td>
    <td>标题</td>
    <td>讲师</td>
    <td>发布日期</td>
  </tr>
  {% for course in courses %}
  <tr>
  <td>{{ forloop.counter }}</td>
  <td><a href="{% url 'course:lessons_list' course.id %}">{{ course.title }}</a></td>
  <td>{{ course.user }}</td>
  <td>{{ course.create_time }}</td>
  </tr>
  {% endfor %}
</table>
</div>
{% endblock %}

course/templates/course/manage_course_list.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
  课程管理
{% endblock %}

{% block content %}
  <div>
    <div class="text-right">
      <a type="button" class="btn btn-default" href="{% url 'course:create_course' %}">添加课程</a>
    </div>
    <div>
      <table class="table table-hover" style="margin-top: 10px">
        <tr>
          <td>序号</td>
          <td>课程标题</td>
          <td>发布日期</td>
          <td>操作</td>
        </tr>
        {% for course in courses %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'course:list_lessons' course.id %}">{{ course.title }}</a></td>
            <td>{{ course.create_time | date:"Y-m-d" }}</td>
            <td>
              <!-- Button trigger modal -->
              <a data-toggle="modal" data-target="#renameModal{{ course.id }}">
                <span class="glyphicon glyphicon-pencil"></span>
              </a>
              <a data-toggle="modal" data-target="#delModal{{ course.id }}">
                <span class="glyphicon glyphicon-trash"></span>
              </a>
              <!-- Modal rename -->
              <div class="modal fade" id="renameModal{{ course.id }}" tabindex="-1" role="dialog"
                   aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                              aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">修改名称</h4>
                    </div>
                    <form action="{% url 'article:rename_article_column' %}" method="post">
                      {% csrf_token %}
                      <div class="modal-body">
                        <input type="hidden" name="column_id" value="{{ course.id }}">
                        {% render_field column_form.column class="form-control" placeholder=column.column %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button type="submit" class="btn btn-primary">确认</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <!-- Modal del -->
              <div class="modal fade" id="delModal{{ course.id }}" tabindex="-1" role="dialog"
                   aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                              aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">确认删除</h4>
                    </div>
                    <form action="{% url 'course:delete_course' course.id %}" method="post">
                      {% csrf_token %}
                      <div class="modal-body">
{#                        <input type="hidden" name="column_id" value="{{ course.id }}">#}
                        <p><strong>{{ course.title }}</strong></p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button type="submit" class="btn btn-primary">确认</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        {% endfor %}

      </table>
    </div>
  </div>
{#  <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>#}
{#  <script type="text/javascript">#}
{#  function getCookie(name) {#}
{#      var cookieValue = null;#}
{#      if (document.cookie && document.cookie != '') {#}
{#          var cookies = document.cookie.split(';');#}
{#          for (var i = 0; i < cookies.length; i++) {#}
{#              var cookie = jquery.trim(cookies[i])#}
{#              if (cookie.substring(0, name.length += 1) == (name + '=')) {#}
{#                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));#}
{#                  break;#}
{#              }#}
{#          }#}
{#      }#}
{#      return cookieValue;#}
{#  }#}
{##}
{#  $(document).ready(function () {#}
{#      var csrftoken = getCookie('csrftoken');#}
{#      function csrfSafeMethod(method) {#}
{#          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));#}
{#      }#}
{#      $.ajaxSetup({#}
{#          crossDomain: false,#}
{#          beforeSend: function (xhr, settings) {#}
{#              if (!csrfSafeMethod((settings.type))) {#}
{#                  xhr.setRequestHeader("X-CSRFToken", csrftoken)#}
{#              }#}
{#          }#}
{#      });#}
{#      var onDelete = function () {#}
{#          alert('delete it?');#}
{##}
{#          $.post(this.href, function (data) {#}
{#              if (data.result == 'ok') {#}
{#                  window.location.reload();#}
{#              } else {#}
{#                  alert('sth wrong');#}
{#              }#}
{#          }).fail(function () {#}
{#              alert('erorr');#}
{#          });#}
{#          return false;#}
{#      }#}
{#      $('.delete').click(onDelete);#}
{#  })#}
{#  </script>#}
{% endblock %}

course/templates/course/student_list_lessons.html
{% extends 'base.html' %}

{% block title %}
  课时列表
{% endblock %}

{% block content %}
  <div>
    <div class="text-center">
      <h1>{{ course.title }}</h1>
      <p>课程课时列表</p>
      {% if user in course.student.all %}
        <div class="alert alert-info" role="alert">你正在学习该课程</div>
      {% else %}
        <form action="{% url 'course:lessons_list' course.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" value="{{ course.id }}" name="course_id">
          <button type="submit" class="btn btn-default">学习该课程</button>
        </form>
      {% endif %}
    </div>
    <table class="table table-hover">
      <tr>
        <td>序号</td>
        <td>课时标题</td>
        <td>发布日期</td>
      </tr>
      {% for lesson in course.lesson.all %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a href="{% url 'course:detail_lesson' lesson.id %}">{{ lesson.title }}</a></td>
          <td>{{ lesson.create_time | date:"Y-m-d" }}</td>
        </tr>
      {% empty %}
        <p>对不起，该课程还没有发布</p>
      {% endfor %}
    </table>
  </div>
{% endblock %}