article/urls.py
"""

@Author  : dilless
@Time    : 2018/7/16 1:25
@File    : urls.py
"""
from django.urls import path, re_path

from article import views

app_name = 'article'

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-article-column/', views.rename_article_column, name='rename_article_column'),
    path('del_article_column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('edit-article/<int:article_id>/', views.edit_article, name='edit-article'),
    path('list-article-titles/', views.list_article_titles, name='list_article_titles'),
    path('list-article-detail/<int:article_id>/<slug:slug>/', views.list_article_detail, name='list_article_detail'),
    path('like-article/', views.like_article, name='like_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    path('rename-article-tag/', views.edit_article_tag, name='rename_article_tag'),
]

blog/urls.py
"""

@Author  : dilless
@Time    : 2018/7/12 1:21
@File    : urls.py
"""
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:blog_id>/', views.blog_article, name='blog_article')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


class ArticleColumn(models.Model):
    """
    文章栏目，不设置多级
    """
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    create_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    create_time = models.DateTimeField(default=timezone.now)
    update_time = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name='articles_like', blank=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ('-update_time',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id, self.slug])

    def get_url_path(self):
        return reverse('article:list_article_detail', args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name='comments', on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_time',)

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.commentator, self.article)

article/forms.py
"""

@Author  : dilless
@Time    : 2018/7/16 1:20
@File    : forms.py
"""
from django import forms

from article.models import ArticleColumn, ArticlePost, Comment, ArticleTag


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body')

        labels = {
            'commentator': '昵称',
            'body': '内容',
        }


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag',)
        labels = {
            'tag': '标签',
        }

article/views.py
import redis
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from article.forms import ArticleColumnForm, ArticlePostForm, CommentForm, ArticleTagForm
from article.models import ArticleColumn, ArticlePost, ArticleTag
from mysite import settings

redis_db = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


@login_required(login_url='/account/login/')
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()

        return render(request, 'article/column/article_column.html', {
            'columns': columns,
            'column_form': column_form,
        })

    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user=request.user, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            columns = ArticleColumn.objects.filter(user=request.user)
            column_form = ArticleColumnForm()
            return render(request, 'article/column/article_column.html', {
                'columns': columns,
                'column_form': column_form,
            })


@login_required(login_url='/account/login/')
@require_POST
def rename_article_column(request):
    column_name = request.POST['column']
    column_id = request.POST['column_id']
    line = get_object_or_404(ArticleColumn, id=column_id)
    line.column = column_name
    line.save()
    return redirect('article:article_column')


@login_required(login_url='/account/login/')
@require_POST
def del_article_column(request):
    column_id = request.POST['column_id']
    line = get_object_or_404(ArticleColumn, id=column_id)
    line.delete()
    return redirect('article:article_column')


@login_required(login_url='/account/login/')
def article_post(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                tag_id_list = request.POST.getlist('article_tag')
                for tag_id in tag_id_list:
                    tag = ArticleTag.objects.get(id=tag_id)
                    new_article.article_tag.add(tag)
                return redirect('article:article_list')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        this_article_column = ''
        return render(request, 'article/column/article_post.html', {
            'article_post_form': article_post_form,
            'article_columns': article_columns,
            'this_article_column': this_article_column,
            'article_tags': article_tags
        })


@login_required(login_url='/account/login/')
def article_list(request):
    # articles = ArticlePost.objects.filter(author=request.user)
    # return render(request, 'article/column/article_list.html', {
    #     'articles': articles,
    # })
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 5)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        articles = current_page.object_list
    return render(request, 'article/column/article_list.html', {
        'articles': articles,
        'page': current_page,
    })


@login_required(login_url=reverse_lazy('account:user_login'))
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, 'article/column/article_detail.html', {
        'article': article
    })


@login_required(login_url=reverse_lazy('account:user_login'))
@require_POST
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return redirect('article:article_list')
    except:
        return HttpResponse('2')


@login_required(login_url=reverse_lazy('account:user_login'))
def edit_article(request, article_id):
    if request.method == 'GET':
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        article_tags = request.user.tag.all()
        article_tags_chose = article.article_tag.all()
        this_article_form = ArticlePostForm(initial={
            'title': article.title,
            'body': article.body,
        })
        this_article_column = article.column
        return render(request, 'article/column/article_post.html', {
            'article_post_form': this_article_form,
            'article_columns': article_columns,
            'this_article_column': this_article_column,
            'article_tags': article_tags,
            'article_tags_chose': article_tags_chose
        })
    if request.method == 'POST':
        article = get_object_or_404(ArticlePost, id=article_id)
        edit_article_form = ArticlePostForm(data=request.POST)
        if edit_article_form.is_valid():
            cd = edit_article_form.cleaned_data
            try:
                article.title = cd['title']
                article.body = cd['body']
                article.column = request.user.article_column.get(id=request.POST['column_id'])
                article.save()
                tag_id_list = request.POST.getlist('article_tag')
                tags_chose = article.article_tag.all()
                for tag in tags_chose:
                    article.article_tag.remove(tag)
                for tag_id in tag_id_list:
                    tag = ArticleTag.objects.get(id=tag_id)
                    article.article_tag.add(tag)
                return redirect('article:article_detail', article_id, article.slug)
            except:
                return HttpResponse('error')
        return HttpResponse('error2')


def list_article_titles(request):
    username = request.GET.get('username')
    user_info = None
    if username:
        user = User.objects.get(username=username)
        articles_title = ArticlePost.objects.filter(author=user)
        try:
            user_info = user.userinfo
        except:
            user_info = None
    else:
        articles_title = ArticlePost.objects.all()
    paginator = Paginator(articles_title, 5)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(1)
        articles = current_page.object_list
    if username:
        return render(request, 'article/list/author_article_titles.html', {
            'articles': articles,
            'page': current_page,
            'user_info': user_info,
        })
    else:
        return render(request, 'article/list/article_titles.html', {
            'articles': articles,
            'page': current_page,
        })


def list_article_detail(request, article_id, slug):
    article = get_object_or_404(ArticlePost, id=article_id, slug=slug)
    total_views = redis_db.incr('article:{}:views'.format(article_id))
    redis_db.zincrby('article_ranking', article_id, 1)

    article_ranking = redis_db.zrange('article_ranking', 0, -1, desc=True)[:10]
    article_ranking_ids = [int(article_ranking_id) for article_ranking_id in article_ranking]
    most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))
    most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))

    # 推荐相似文章
    article_tags_ids = article.article_tag.values_list('id', flat=True)
    similar_articles = ArticlePost.objects.filter(article_tag__in=article_tags_ids).exclude(id=article.id)
    similar_articles = similar_articles.annotate(same_tags=Count('article_tag')).order_by('-same_tags', '-create_time')

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'article/list/article_detail.html', {
        'article': article,
        'total_views': total_views,
        'most_viewed': most_viewed,
        'comment_form': comment_form,
        'similar_articles': similar_articles,
    })


@csrf_exempt
@require_POST
@login_required(login_url=reverse_lazy('account:user_login'))
def like_article(request):
    article_id = request.POST.get('id')
    action = request.POST.get('action')
    if article_id and action:
        try:
            article = ArticlePost.objects.get(id=article_id)

article/templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block title %}
  文章栏目
{% endblock %}

{% block content %}
  <div>
    <p class="text-right">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
        新增栏目
      </button>

      <!-- Modal add -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">新增栏目</h4>
          </div>
          <form action="{% url 'article:article_column' %}" method="post">
            {% csrf_token %}
            <div class="modal-body">
              {#            <input class="form-control" type="text" name="column" placeholder="请输入栏目名称">#}
              {% render_field column_form.column class='form-control' placeholder='请输入栏目名称' %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
              <button type="submit" class="btn btn-primary">保存</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    </p>
    <table class="table table-hover">
      <tr>
        <td>序号</td>
        <td>栏目名称</td>
        <td>操作</td>
      </tr>
      {% for column in columns %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ column.column }}</td>
          <td>
            <!-- Button trigger modal -->
            <a data-toggle="modal" data-target="#renameModal{{ column.id }}">
              <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a data-toggle="modal" data-target="#delModal{{ column.id }}">
              <span class="glyphicon glyphicon-trash"></span>
            </a>

            <!-- Modal rename -->
            <div class="modal fade" id="renameModal{{ column.id }}" tabindex="-1" role="dialog"
                 aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">修改名称</h4>
                  </div>
                  <form action="{% url 'article:rename_article_column' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                      <input type="hidden" name="column_id" value="{{ column.id }}">
                      {% render_field column_form.column class="form-control" placeholder=column.column %}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                      <button type="submit" class="btn btn-primary">确认</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <!-- Modal del -->
            <div class="modal fade" id="delModal{{ column.id }}" tabindex="-1" role="dialog"
                 aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">确认删除</h4>
                  </div>
                  <form action="{% url 'article:del_article_column' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                      <input type="hidden" name="column_id" value="{{ column.id }}">
                      <p><strong>{{ column.column }}</strong></p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                      <button type="submit" class="btn btn-primary">确认</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </td>
        </tr>
      {% empty %}
        <p>你还没有设置栏目，太懒了-_-</p>
      {% endfor %}
    </table>
  </div>
{% endblock %}

article/templates/article/column/article_detail.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
  文章详情
{% endblock %}

{% block content %}
  <div>
    <header>
      <h1>{{ article.title }}</h1>
      <p>{{ user.username }}</p>
    </header>
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.min.css' %}">
    <div id="editormd-view">
      <textarea id="append-test" style="display: none">{{ article.body }}</textarea>
    </div>
  </div>
  <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'editor/lib/marked.min.js' %}"></script>
  <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
  <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
  <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
  <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
  <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
  <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
  <script src="{% static 'editor/editormd.min.js' %}"></script>

  <script type="text/javascript">
  $(function () {
      editormd.markdownToHTML("editormd-view", {
          htmlDecode: "style, script, iframe",
          emoji: true,
          taskList: true,
          tex: true,
          flowChart: true,
          sequeceDiagram: true,
      });
  });
  </script>
{% endblock %}

article/templates/article/column/article_list.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
  文章列表
{% endblock %}

{% block content %}
  <div>
    <table class="table table-hover">
      <tr>
        <td>序号</td>
        <td>标题</td>
        <td>栏目</td>
        <td>操作</td>
      </tr>
      {% for article in articles %}
        <tr id="{{ article.id }}">
          <td>{{ forloop.counter }}</td>
          <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
          <td>{{ article.column }}</td>
          <td>
            <a href="{% url 'article:edit-article' article.id %}">
              <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a data-toggle="modal" data-target="#delModal{{ article.id }}">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </td>
        </tr>
        <div class="modal fade" id="delModal{{ article.id }}" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">确认删除</h4>
              </div>
              <form action="{% url 'article:del_article' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                  <input type="hidden" name="article_id" value="{{ article.id }}">
                  <p><strong>删除《{{ article.title }}》后无法恢复，请确认</strong></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                  <button type="submit" class="btn btn-primary">确认</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    </table>
    {% include 'paginator.html' %}
  </div>
{% endblock %}

article/templates/article/column/article_post.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
  文章栏目
{% endblock %}

{% block content %}
  <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
  <div class="">
    <form class="form-horizontal" action="." method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ article_post_form.title.id_for_label }}"
               class="col-sm-2">{{ article_post_form.title.label }}</label>
        {% render_field article_post_form.title class='form-control' %}
      </div>
      <div class="form-group">
        <label for="id_select_column">栏目：</label>
        <select class="form-control" id="id_select_column" name="column_id">
          {% for column in article_columns %}
            {% ifequal column this_article_column %}
              <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
            {% else %}
              <option value="{{ column.id }}">{{ column.column }}</option>
            {% endifequal %}
          {% endfor %}
        </select>
      </div>
      {% for article_tag in article_tags %}
        {% if article_tag in article_tags_chose %}
          <div class="checkbox-inline">
            <label>
              <input type="checkbox" value="{{ article_tag.id }}" name="article_tag" id="tag{{ article_tag.id }}" checked>
              {{ article_tag.tag }}
            </label>
          </div>
        {% else %}
          <div class="checkbox-inline">
            <label>
              <input type="checkbox" value="{{ article_tag.id }}" name="article_tag" id="tag{{ article_tag.id }}">
              {{ article_tag.tag }}
            </label>
          </div>
        {% endif %}
      {% empty %}
        <p>你还没有设置标签，请<a href="{% url 'article:article_tag' %}">添加标签</a></p>
      {% endfor %}

      <div class="form-group">
        <label for="{{ article_post_form.body.id_for_label }}">{{ article_post_form.body.label }}</label>
        {#      {% render_field article_post_form.body class="form-control" %}#}
        <div id="editormd">
          <textarea id="{{ article_post_form.body.id_for_label }}"
                    style="display:none;" name="body">{{ article_post_form.body|striptags }}</textarea>
        </div>

      </div>
      <div class="form-group">
        <div class="text-right">
          <input type="submit" class="btn btn-default" value="发布">
        </div>
      </div>
    </form>
  </div>
  <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'editor/editormd.min.js' %}"></script>
  <script type="text/javascript">
      $(function () {
          var editor = editormd("editormd", {
              width: '100%',
              height: '640,',
              syncScrolling: 'single',
              path: "{% static 'editor/lib/' %}"
          });
      });
  </script>
{% endblock %}