account/urls.py
"""

@Author  : dilless
@Time    : 2018/7/12 22:12
@File    : urls.py
"""
from django.contrib.auth import views as auth_views
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    # path('login/', views.user_login, name='user_login'),
    path('login/', auth_views.login, {'template_name': 'account/login.html'}, name='user_login'),
    path('logout/', auth_views.logout, {'template_name': 'account/logout.html'}, name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.password_change, {"post_change_redirect": "/account/password-change-done",
                                                          'template_name': 'account/password_change_form.html'},
         name='password_change'),
    path('password-change-done/', auth_views.password_change_done,
         {'template_name': 'account/password_change_done.html'}, name='password_change_done'),
    path('password-reset/', auth_views.password_reset, {"template_name": "account/password_reset_form.html",
                                                        "email_template_name": "account/password_reset_email.html",
                                                        "subject_template_name": "account/password_reset_subject.txt",
                                                        "post_reset_redirect": "/account/password-reset-done"},
         name="password_reset"),
    path('password-reset-done/', auth_views.password_reset_done, {"template_name": "account/password_reset_done.html"},
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.password_reset_confirm,
         {"template_name": "account/password_reset_confirm.html",
          "post_reset_redirect": "/account/password-reset-complete"}, name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.password_reset_complete,
         {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name='edit_my_information'),
    path('my-image/', views.my_image, name='my_image'),
]

article/urls.py
"""

@Author  : dilless
@Time    : 2018/7/16 1:25
@File    : urls.py
"""
from django.urls import path, re_path

from article import views

app_name = 'article'

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-article-column/', views.rename_article_column, name='rename_article_column'),
    path('del_article_column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/<slug:slug>/', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('edit-article/<int:article_id>/', views.edit_article, name='edit-article'),
    path('list-article-titles/', views.list_article_titles, name='list_article_titles'),
    path('list-article-detail/<int:article_id>/<slug:slug>/', views.list_article_detail, name='list_article_detail'),
    path('like-article/', views.like_article, name='like_article'),
    path('article-tag/', views.article_tag, name='article_tag'),
    path('del-article-tag/', views.del_article_tag, name='del_article_tag'),
    path('rename-article-tag/', views.edit_article_tag, name='rename_article_tag'),
]

blog/urls.py
"""

@Author  : dilless
@Time    : 2018/7/12 1:21
@File    : urls.py
"""
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:blog_id>/', views.blog_article, name='blog_article')
]

course/urls.py
"""

@Author  : dilless
@Time    : 2018/7/18 23:54
@File    : urls.py
"""
from django.urls import path

from course.views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, \
    CreateLessonView, ListLessonsView, DetailLessonView, StudentListLessonView

app_name = 'course'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('course-list/', CourseListView.as_view(), name='course_list'),
    path('manage-course/', ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(), name='delete_course'),
    path('create-lesson/', CreateLessonView.as_view(), name='create_lesson'),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name='list_lessons'),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name='detail_lesson'),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name='lessons_list'),
]

image/urls.py
"""

@Author  : dilless
@Time    : 2018/7/18 19:39
@File    : urls.py
"""
from django.urls import path

from image import views

app_name = 'image'

urlpatterns = [
    path('upload-image/', views.upload_image, name='upload_image'),
    path('list-images/', views.list_images, name='list_images'),
    path('del-image/', views.del_image, name='del_image'),
    path('images/', views.falls_images, name='falls_images'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('image/', include('image.urls')),
    path('course/', include('course.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap -->
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <!-- my style-->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
  <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
  <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
{% include 'header.html' %}
<body>
<div class="container">
  {% block centent %}{% endblock %}
</div>
{% include 'footer.html' %}
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/footer.html
<footer class="footer">
  <hr>
  <div class="container">
    <p class="text-muted">
      <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>黄波的博客 --
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>友情链接：<a
            href="http://glyphicons.com/">Glyphicons</a>
    </p>
  </div>
</footer>

templates/header.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-head">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'blog:blog_title' %}">
        <img src="{% static 'images/logo.png' %}" width="100px">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'index' %}">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
        <li><a href="{% url 'article:list_article_titles' %}">文章</a></li>
        <li><a href="{% url 'image:falls_images' %}">美图</a></li>
        <li><a href="{% url 'course:course_list' %}">课程列表</a></li>
        <li><a href="{% url 'course:about' %}">关于</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="true">
                {{ user.username }}
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                <li><a href="{% url 'account:my_information' %}">个人信息</a> </li>
                <li><a href="{% url 'article:article_column' %}">后台管理</a> </li>
              </ul>
            </div>
          </li>
          <li><a href="{% url 'account:user_logout' %}">退出登录</a></li>
        {% else %}
          <li><a href="{% url 'account:user_login' %}">登录/注册</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
首页
{% endblock %}

{% block content %}
<div>
<div class="text-center">
<h1>欢迎</h1>
  <h3>人生苦短，请用Python</h3>
  <h2>Django牛逼</h2>
  <img src="{% static 'images/2.jpg' %}" alt="2B小姐姐" width="400px">
</div>
</div>
{% endblock %}

templates/paginator.html
<div class="text-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if page.has_previous %}
        <li>
          <a href="?page={{ page.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      <li class="current">
        <span>第{{ page.number }}页/共{{ page.paginator.num_pages }}页</span>
      </li>
      {% if page.has_next %}
        <li>
          <a href="?page={{ page.next_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>